# Generated by Django 4.1.3 on 2022-11-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAMA', models.CharField(max_length=30)),
                ('NPM', models.CharField(max_length=20)),
                ('ALAMAT', models.TextField()),
                ('TETALA', models.DateField()),
                ('EMAIL', models.EmailField(default='@gmail.com', max_length=254)),
                ('KODEPOS', models.CharField(max_length=5)),
            ],
        ),
    ]
