# Generated by Django 4.1.3 on 2022-11-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='alamat',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='tahu@gmail.com', max_length=254),
        ),
    ]
