# Generated by Django 4.1.3 on 2022-12-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_habib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=254),
        ),
    ]
