# Generated by Django 4.1.3 on 2022-11-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='alamat',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
