# Generated by Django 4.1.3 on 2022-11-23 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_alamat'),
    ]

    operations = [
        migrations.CreateModel(
            name='devi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('judul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.about')),
            ],
        ),
    ]
