# Generated by Django 4.1.3 on 2022-12-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_th'),
    ]

    operations = [
        migrations.DeleteModel(
            name='th',
        ),
    ]
