# Generated by Django 4.1.3 on 2022-12-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_delete_th'),
    ]

    operations = [
        migrations.CreateModel(
            name='th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPM', models.CharField(max_length=20)),
                ('Judul_skripsi', models.CharField(max_length=20)),
                ('Abstrak', models.CharField(max_length=500)),
                ('Pembimbing', models.CharField(max_length=30)),
                ('Kode_skripsi', models.IntegerField(max_length=1)),
                ('Nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.mhs')),
            ],
        ),
    ]
