# Generated by Django 4.1.3 on 2022-12-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='th',
            name='Kode_skripsi',
            field=models.IntegerField(null=True),
        ),
    ]
