# Generated by Django 4.1.3 on 2022-12-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_th_kode_skripsi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='th',
            new_name='skripsi',
        ),
    ]
