# Generated by Django 4.1.3 on 2022-12-14 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_rename_th_skripsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kode_matakuliah', models.CharField(max_length=7)),
                ('Nilai_angka', models.FloatField()),
                ('Nilai_huruf', models.CharField(max_length=2)),
                ('NAMA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.mhs')),
            ],
        ),
    ]
